### ISSUE TITLE
Problem with porting

### ISSUE THREAD

**Issue by hiperiondev** [lotoohe-space/XTinyModbus#1]
I'm porting your code to ESP8266_RTOS_SDK 

I can see two problems:
1.- All comments in Chinese: Very difficult to translate one by one. Please comment in English for more agile porting and help with issues
2.- UTF vs ASCII src: Import code generate strange/non printable characters that can create problems/errors in non Chinese environment. Please convert to ascii all code

Another possible change is separate modbus programs from system implementation. Now is a monolithic project.

**Comment by lotoohe-space** [comment]
Thank you for your feedback, I will solve these problems in later versions.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hiperión"<notifications@github.com&gt;; 
发送时间: 2020年9月8日(星期二) 下午5:30
收件人: "lotoohe-space/XTinyModbus"<XTinyModbus@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [lotoohe-space/XTinyModbus] Problem with porting (#1)





 
I'm porting your code to ESP8266_RTOS_SDK
 I can see two problems:
 1.- All comments in Chinese: Very difficult to translate one by one. Please comment in English for more agile porting and help with issues
 2.- UTF vs ASCII src: Import code generate strange/non printable characters that can create problems/errors in non Chinese environment. Please convert to ascii all code

**Comment by hiperiondev** [comment]
This is my first attempt for porting.
Compile but not tested yet, with code reordered

https://github.com/hiperiondev/esp8266-XTinyModbus

**Comment by lotoohe-space** [comment]
OK, I'll keep an eye on it. I rarely use esp8266.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hiperión"<notifications@github.com&gt;; 
发送时间: 2020年9月8日(星期二) 晚上6:23
收件人: "lotoohe-space/XTinyModbus"<XTinyModbus@noreply.github.com&gt;; 
抄送: "1358745329"<1358745329@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [lotoohe-space/XTinyModbus] Problem with porting (#1)





 
This is my first attempt for porting.
 Compile but not tested yet, with code reordered
 
https://github.com/hiperiondev/esp8266-XTinyModbus

**Comment by hiperiondev** [comment]
I'm fished to probe my porting but not respond with modpoll testing
    #modpoll -m rtu -b 115200 -d 8 -s 1 -p none -a 1 /dev/ttyUSB0

uart task receive communication and pass byte received to MDSSerialRecvByte

A hardware timer call every 100uS to MDSTimeHandler100US

And a loop call MDS_RTU_Loop (in MDS_RTU_APP)

But never respond.

I think I've not understanding the process

**Comment by Yanbenchu** [comment]
楼主大神，在用你的这个程序，我发现个不理解的地方。就是在读取保存寄存器数据，超过5个寄存器时，会出现，读出来的数据重新开始第一个数据的结果，十分疑惑，如下图，但是我看了半天感觉好像你的程序没错啊，我查找不出原因，万望赐教！
![173258j17m7ic12mr7ytvk](https://user-images.githubusercontent.com/57178379/92895266-efbcac00-f44d-11ea-8ee5-6cb6c452f4da.png)

**Comment by lotoohe-space** [comment]
图片看不到，请加QQ群419833232



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2020年9月11日(星期五) 下午4:44
收件人: "lotoohe-space/XTinyModbus"<XTinyModbus@noreply.github.com&gt;; 
抄送: "1358745329"<1358745329@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [lotoohe-space/XTinyModbus] Problem with porting (#1)





 
楼主大神，在用你的这个程序，我发现个不理解的地方。就是在读取保存寄存器数据，超过5个寄存器时，会出现，读出来的数据重新开始第一个数据的结果，十分疑惑，如下图，但是我看了半天感觉好像你的程序没错啊，我查找不出原因，万望赐教！

**Comment by lotoohe-space** [comment]
2020/9/24 <br>
Added the function of not polling when the slave is disconnected, the master can use the MDM_RTU_CB_SetDisPollEnFlag function to set it,<br>
You can use the MDM_RTU_CB_ClrDisFlag function to reset. <br>
Add a simple host sending controller. <br>
Fix the BUG of mixed call of host blocking mode and non-blocking mode. <br>
All comments in the code are modified to English. <br>

**Comment by lotoohe-space** [comment]
2020/9/24 <br&gt;
Added the function of not polling when the slave is disconnected, the master can use the MDM_RTU_CB_SetDisPollEnFlag function to set it,<br&gt;
You can use the MDM_RTU_CB_ClrDisFlag function to reset. <br&gt;
Add a simple host sending controller. <br&gt;
Fix the BUG of mixed call of host blocking mode and non-blocking mode. <br&gt;
All comments in the code are modified to English. <br&gt;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lotoohe-space/XTinyModbus"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月8日(星期二) 晚上11:06
收件人:&nbsp;"lotoohe-space/XTinyModbus"<XTinyModbus@noreply.github.com&gt;;
抄送:&nbsp;"1358745329"<1358745329@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [lotoohe-space/XTinyModbus] Problem with porting (#1)





 
I'm fished to probe my porting but not respond with modpoll testing
 #modpoll -m rtu -b 115200 -d 8 -s 1 -p none -a 1 /dev/ttyUSB0
 
uart task receive communication and pass byte received to MDSSerialRecvByte
 
A hardware timer call every 100uS to MDSTimeHandler100US
 
And a loop call MDS_RTU_Loop (in MDS_RTU_APP)
 
But never respond.
 
I think I've not understanding the process
